### ISSUE TITLE
pvpmanager.nopvp not working.

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#255]
I'm trying to deny a rank from being tagged or tagging in PvP, and also stopping PvP with that rank.
I've given them the two below permissions but this makes no difference, they can still be in any PvP like normal.
```
pvpmanager.nocombat - Exempts a player from being placed in combat
pvpmanager.nopvp - Players with this permission always have PvP disabled
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Give a role pvpmanager.nopvp & pvpmanager.nocombat 
2. Attack player with those perms.
3. PvP as normal.

**Expected behaviour**
To deny the player with those permissions the ability to PvP from being attacked and to attack.

**Plugin and Server version**
PvPManager version 3.13.25
git-Paper-1618 (MC: 1.12.2)

**Comment by ChanceSD** [comment]
I still didn't test but that should be working. Can you check if maybe they are in an excluded world?

**Comment by TomLewis** [comment]
> I still didn't test but that should be working. Can you check if maybe they are in an excluded world?

I don't have any excluded worlds!
This is my config if it helps

https://gist.github.com/TomLewis/7c97d08c4b410b805ee3cb0283910fa4

**Comment by ChanceSD** [comment]
Alright, so I'm testing it right, "pvpmanager.nocombat" just makes it so they don't get tagged btw, so no combat countdown, etc. That one seems to be working as expected.
About "pvpmanager.nopvp", it also seems to work, I added the permission and the player got their pvp disabled but this requires a relog, it will only be disabled when the player logs out and back in. And the player can still toggle his pvp back on if he has permission to use /pvp so that must be removed. Did you not get the same results? Maybe I'm missing something or maybe the player you tested on was online and didn't relog.

**Comment by TomLewis** [comment]
I did not get the same results!
Neither did anything for me.

I am using Paper 1.12.2

**Comment by ChanceSD** [comment]
Does the player you're testing on have permission to toggle PvP? I think they got their PvP toggled and it saved their cooldown to users.yml. Then when they login it just loads from database instead of checking the permission.
I'm changing it so that it checks the permission regardless and that they can't toggle PvP if they have the nopvp permission. You shouldn't have given them permission to toggle PvP if you want them to have PvP disabled though.

**Comment by ChanceSD** [comment]
Try the newest version on Spigot 3.14.4 should fix this.

**Comment by TomLewis** [comment]
Thank you, I will queue this up for tomorrows reboot!

**Comment by TomLewis** [comment]
Update on this, I never got this to work.

I got my server updated to 1.18.2 since I created this ticket and it still persists.

The player that has the permission can not attack people, but can be attacked by another player. 
So they are prevented from PvP but not protected from it.

And it requires a relog for that permission to be read.

**Comment by TomLewis** [comment]
Bumping this, I really want to be able to toggle a players PvP ia command and permission.

**Comment by ChanceSD** [comment]
> Bumping this, I really want to be able to toggle a players PvP ia command and permission.

I still have more or less the same reply I did back then, those features seem to work properly for other people as well.
I reopened your ticket on discord, let's see if we can figure that through there please, should be faster to exchange information about this.

**Comment by TomLewis** [comment]
if anyone else finds this ticket, this was due to the intergration with bounty hunters. Disable that in the config if you use BountyHunters!
